module.exports = {
  ANALYTICS_URL_PROD: 'ANALYTICS_URL_PROD',
  ANALYTICS_URL_TEST: 'ANALYTICS_URL_TEST',
  NLP_URL_PROD: 'NLP_URL_PROD',
  NLP_URL_TEST: 'NLP_URL_TEST',
  SEND_LOG_URL: 'SEND_LOG_URL'
};
